package chordax_dev_team.chordax_songs.model;

import java.util.ArrayList;
import java.util.List;

import chordax_dev_team.chordax_songs.model.enums.LineType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "Verse model containing lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Line {

	@Schema(description = "Autogenerated line's Id number.")
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Schema(description = "Type of line", example = "VERSE")
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private LineType lineType;

	@Schema(description = "Lyrics of the line", example = "Feeling my way through the darkness")
	@Column(nullable = false)
	private String lyrics;

	@Schema(description = "List of tones with chords and positions")
							// prevents deletion of Tone(s) that are shared with other Line(s)
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE})
	@JoinTable(
			name = "line_tone",
			joinColumns = @JoinColumn(name = "line_id"),
			inverseJoinColumns = @JoinColumn(name = "tone_id")
	)
	private List<Tone> tones = new ArrayList<>();
}
