package chordax_dev_team.chordax_songs.model;

import java.util.ArrayList;
import java.util.List;

import chordax_dev_team.chordax_songs.model.enums.LineType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "Verse model containing lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class Line {

	@Schema(description = "Autogenerated line's Id number.")
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Schema(description = "Type of line", example = "VERSE")
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private LineType lineType;

	@Schema(description = "Lyrics of the line", example = "Feeling my way through the darkness")
	@Column(nullable = false)
	private String lyrics;

	@Schema(description = "The song this line belongs to")
	@ManyToOne(optional = false)
	@JoinColumn(name = "song_id", nullable = false)
	@JsonIgnore
	private Song song;

	@Schema(description = "List of tones with chords and positions")
							// prevents deletion of Tone(s) that are shared with other Line(s)
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinTable(
			name = "line_tone",
			joinColumns = @JoinColumn(name = "line_id"),
			inverseJoinColumns = @JoinColumn(name = "tone_id")
	)
	private List<Tone> tones = new ArrayList<>();

	public Line(LineType lineType, String lyrics, Song song, List<Tone> tones) {
		this.lineType = lineType;
		this.lyrics = lyrics;
		this.song = song;
		this.tones = tones;
	}
}

//SELECT
//		s.entered_at,
//		s.id AS song_id,
//		s.user_id,
//		s.author,
//		s.composer,
//		s.title,
//		l.id AS line_id,
//		l.line_type,
//		l.lyrics,
//		t.position,
//		t.id AS tone_id,
//		t.chord
//		FROM song s
//		JOIN line l ON s.id = l.song_id
//		JOIN line_tone lt ON l.id = lt.line_id
//		JOIN tone t ON lt.tone_id = t.id;