package chordax_dev_team.chordax_songs.model;

import java.time.LocalDateTime;
import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

@Schema(description = "Song model with lines containing lyrics and chords.")
@Entity
@Data
public class Song {

	@Schema(description = "Autogenerated song's ID number.", example = "3")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column
	private long id;

	@Schema(description = "Title of the song.", example = "Wake Me Up")
	@NotBlank(message = "Title is required")
	@Column(nullable = false)
	private String title;

	@Schema(description = "Composer of the song.", example = "Avicii, Aloe Blacc, Mike Einziger")
	private String composer;

	@Schema(description = "Author of the lyrics.", example = "Aloe Blacc")
	private String author;

	@Schema(description = "Timestamp of when the song was entered.", example = "2025-09-11T05:05:05")
	@Column(nullable = false)
	private LocalDateTime enteredAt;

	@Schema(description = "ID of the user who submitted the song.", example = "1")
	@Column(nullable = false)
	private long userId;

	@Schema(description = "List of lines containing lyrics and associated chords.")
	@OneToMany(mappedBy="song")
	private List<Line> lines;
}

