package chordax_dev_team.chordax_songs.model;

import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.JoinTable;
import jakarta.persistence.JoinColumn;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.Singular;

@Schema(description = "Song model with verses conataining lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Song {

	@Schema(nullable = false, description = "Autogenerated song's Id number.")
	@Id
	@Column(name="id")
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Column(nullable = false)
	private String title;
	
	@Column(nullable = false)
	private long userId;

	@OneToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "song_verses", joinColumns = @JoinColumn(name = "song_id"), inverseJoinColumns = @JoinColumn(name = "verse_id"))
	private List<Verse> verses;

}
