package chordax_dev_team.chordax_songs.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "Tone model with chords contaings it note and position along lyrics.")
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Tone {
	
	@Schema(nullable = false, description = "Autogenerated verse's Id number.")
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;
	
	@Column(nullable = false)
	private String tone;
	
	@Column(nullable = false)
	private int position;
	
//	@Column(nullable = false)
//	private long verseId;

}
