package chordax_dev_team.chordax_songs.model;

import java.util.List;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.JoinTable;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.JoinColumn;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Schema(description = "Verse model containing lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Verse {

	@Schema(nullable = false, description = "Autogenerated verse's Id number.")
	@Id
	@Column
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long id;

	@Column(nullable = false)
	private String lyrics;

	@OneToMany(cascade = CascadeType.ALL)
	@JoinTable(name = "verse_tones", joinColumns = @JoinColumn(name = "verse_id"), inverseJoinColumns = @JoinColumn(name = "tone_id"))
	private List<Tone> tones;

//	public long getId() {
//		return id;
//	}
//
//	public void setId(long id) {
//		this.id = id;
//	}
//
//	public String getLyrics() {
//		return lyrics;
//	}
//
//	public void setLyrics(String lyrics) {
//		this.lyrics = lyrics;
//	}
//
//	public List<Tone> getTones() {
//		return tones;
//	}
//
//	public void setTones(List<Tone> tones) {
//		this.tones = tones;
//	}

	
}
