package chordax_dev_team.chordax_songs.song.model;

import chordax_dev_team.chordax_songs.song.model.enums.LineType;
import com.fasterxml.jackson.annotation.JsonIgnore;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;

import java.util.ArrayList;
import java.util.List;

@Schema(description = "Verse model containing lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Line {

	@Schema(description = "Autogenerated line's ID number.", example = "42")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id; // ✅ Use wrapper type for nullability

	@Schema(description = "Type of line", example = "VERSE")
	@Enumerated(EnumType.STRING)
	@Column(nullable = false)
	private LineType lineType;

	@Schema(description = "Lyrics of the line", example = "Feeling my way through the darkness")
	@Column(nullable = false)
	private String lyrics;

	@Schema(description = "The song this line belongs to")
	@ManyToOne(optional = false)
	@JoinColumn(name = "song_id", nullable = false)
	@JsonIgnore // ✅ Prevent circular reference during serialization
	private Song song;

	@Schema(description = "List of tones with chords and positions")
	@ManyToMany(cascade = {CascadeType.PERSIST, CascadeType.MERGE, CascadeType.REFRESH})
	@JoinTable(
			name = "line_tone",
			joinColumns = @JoinColumn(name = "line_id"),
			inverseJoinColumns = @JoinColumn(name = "tone_id")
	)
	private List<Tone> tones = new ArrayList<>();

	// ✅ Convenience constructor for manual instantiation
	public Line(LineType lineType, String lyrics, Song song, List<Tone> tones) {
		this.lineType = lineType;
		this.lyrics = lyrics;
		this.song = song;
		this.tones = tones;
	}
}