package chordax_dev_team.chordax_songs.song.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;
import org.hibernate.annotations.OnDelete;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.LocalDateTime;
import java.util.List;

@Schema(description = "Song model with lines containing lyrics and chords.")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Song {

	private static final Logger logger = LoggerFactory.getLogger(Song.class);

	@Schema(description = "Autogenerated song's ID number.", example = "3")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Schema(description = "Title of the song.", example = "Wake Me Up")
	@NotBlank(message = "Title is required")
	@Column(nullable = false)
	private String title;

	@Schema(description = "Composer of the song.", example = "Avicii, Aloe Blacc, Mike Einziger")
	private String composer;

	@Schema(description = "Author of the lyrics.", example = "Aloe Blacc")
	private String author;

	@Schema(description = "Timestamp of when the song was entered.", example = "2025-09-11T05:05:05")
	@Column(nullable = false)
	private LocalDateTime enteredAt;

	@Schema(description = "ID of the user who submitted the song.", example = "1")
	@Column(nullable = false)
	private Long userId;

	@Schema(description = "List of lines containing lyrics and associated chords.")
	@OneToMany(mappedBy = "song", cascade = CascadeType.ALL, orphanRemoval = true)
	private List<Line> lines;

	@PrePersist
	public void onCreate() {
		if (enteredAt == null) {
			enteredAt = LocalDateTime.now();
		}
		logger.info("Persisting new song: '{}' by userId={} at {}", title, userId, enteredAt);
	}

	@PreUpdate
	public void onUpdate() {
		logger.info("Updating song: '{}' (ID={}) by userId={}", title, id, userId);
	}

	@PostRemove
	public void onDelete() {
		logger.info("Deleting song: '{}' (ID={}) by userId={}", title, id, userId);
	}
}