package chordax_dev_team.chordax_songs.song.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;


@Schema(description = "Tone model with chords contaings it note and position along lyrics.")
@Entity
@Getter
@Setter
@NoArgsConstructor
public class Tone {

	@Schema(description = "Autogenerated tone's Id number.")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column
	private Long id;

	@Schema(description = "Chord name used in the song line.", example = "Bm")
	@Column(nullable = false)
	private String chord;

	@Schema(description = "Position of the chord in milliseconds or beat offset.", example = "0")
	@Column(nullable = false)
	private int position;

	public Tone(String chord, int position) {
		this.chord = chord;
		this.position = position;
	}
}
