package chordax_dev_team.chordax_songs.song.model;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.*;
import lombok.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;

@Schema(description = "Tone model with chords containing its note and position along lyrics.")
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Tone {

	private static final Logger logger = LoggerFactory.getLogger(Tone.class);

	@Schema(description = "Autogenerated tone's ID number.")
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Schema(description = "Chord name used in the song line.", example = "Bm")
	@Column(nullable = false)
	private String chord;

	@Schema(description = "Position of the chord in milliseconds or beat offset.", example = "0")
	@Column(nullable = false)
	private int position;

	public Tone(String chord, int position) {
		this.chord = chord;
		this.position = position;
	}

	@PostPersist
	public void onCreate() {
		logger.info("Persisted new tone: '{}' at position {}", chord, position);
	}

	@PreUpdate
	public void onUpdate() {
		logger.info("Updating tone ID={} to chord '{}' at position {}", id, chord, position);
	}
}