spring:
########################### CONFIG ############################################
  config.import: optional:configserver:http://localhost:8888

### WHAT CONFIGURED:
###### - EUREKA - SERVICE DISCOVERY - CLIENT
###### - PORT

########################### APP'S NAME #################################
  application.name: chordax_songs