spring:
  application.name: chordax_songs

########################### H2 ############################################
#----------- to set h2 database connection -----------------
  datasource:
    url: jdbc:h2:mem:chordax
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
#----------- to insert data at start from resources/data.sql file -----------------
    defer-datasource-initialization: true
#----------- to open h2 console in browser -----------------
  h2.console.enabled: true

########################### SERVER ############################################
#server.error:
#  include-stacktrace: always
#  include-exception: true

########################### LOGGING ############################################
logging.level.org.hibernate:
  tool.hbm2ddl: DEBUG
  SQL: DEBUG

########################### SWAGGER ############################################
springdoc.api-docs:
  title: Chordax Songs API
  version: 1.0.0
  description: REST API for managing songs, lyrics, and chords

########################### EUREKA ############################################
eureka:
  client.serviceUrl.defaultZone: http://localhost:8765/eureka
  instance.preferIpAddress: true