spring.application.name=chordax_songs

########################### SEVER ############################################
#server.error.include-stacktrace=always
#server.error.include-exception=true

########################### LOGGING ############################################
#logging.level.org.hibernate.tool.hbm2ddl=DEBUG
#logging.level.org.hibernate.SQL=DEBUG

########################### H2 ############################################
#----------- to set h2 database connection -----------------
spring.datasource.url=jdbc:h2:mem:chordax
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
sprinr.jpa.show-sql=true
#----------- to open h2 console in browser -----------------
spring.h2.console.enabled=true
#----------- to insert data at start from resources/data.sql file -----------------
spring.jpa.defer-datasource-initialization=true

########################### SWAGGER ############################################
springdoc.api-docs.title=Chordax Songs API
springdoc.api-docs.version=1.0.0
springdoc.api-docs.description=REST API for managing songs, lyrics, and chords

########################### EUREKA ############################################
eureka.client.serviceUrl.defaultZone=http://localhost:8765/eureka
eureka.instance.preferIpAddress=true